blog/urls.py
from django.urls import include, path
from . import views

app_name = 'blog'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('details/<int:id>/',views.details, name='details'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:id>/edit', views.post_edit, name='post_edit')
    #path('/form', views.form, name='form'),
    
    
    
]

blog_application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),

]

blog/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    

    def __str__(self):
        return self.title

    

       

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post

class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ( 'username','email', 'password1', )

class PostForm(forms.ModelForm):

    class Meta:
        model= Post
        fields = ( 'title', 'text',)

blog/views.py
from django.shortcuts import  render, redirect
from django.shortcuts import  get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.shortcuts import redirect

from .forms import SignUpForm
from .forms import PostForm

from .models import Post

  #List of all the Post 
def index(request):
    post = Post.objects.all()

    context = {
        'title':'These are the Latest Posts',
        'post': post,
        }
    return render(request,'blog/index.html', context)
 #Posts detail page
def details(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post': post,
        }
    return render(request,'blog/details.html', context)
'''
def form(request):
    context = {
        'title':'Form',
    }
    return render(request,'blog/form.html', context) 
'''
 # signup page for user
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect('blog:index')
    else:
        form = SignUpForm()
    return render(request, 'blog/signup.html', {'form': form})

# add the new post
def post_new(request):

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            post.save()
            return redirect('blog:details', id=post.id)
    else:
        form = PostForm()
    return render(request, 'blog/edit.html', {'form': form})    
   
def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == "POST":
        form = PostForm(request.POST, instance = post)
        if form.is_valid():
            post = form.save()
            post.save()
            return redirect('blog:details', id=post.id) 
    else:
        form = PostForm(instance = post)
    return render(request, 'blog/edit.html', {'form': form})          

blog/templates/blog/base.html
{% load static %}
<html>
<head>
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="main.js"></script>
</head>
<body>
    <header class="container center-align">
            <nav class="navbar navbar-default">
                    <div class="container-fluid">
                      <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">Blog Application</a>
                        </div>
                  
                      <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="{% url 'blog:signup' %}">Signup <span class="sr-only">(current)</span></a></li>
                                <li><a href="{% url 'blog:post_new' %}">Add post</a></li>

                            </ul>
                        </div> 
                    </div>
            </nav>               


    </header> 
    <!-- <h1 class="center-align">Blog Application</h1> -->
   <div class="container">
        {%  block content %}
        {% endblock %}
    </div>
      
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block javascript %}
    {% endblock %}

</body>
</html>

blog/templates/blog/details.html
{% extends 'blog/base.html' %}

{% block content %}
<h3 class="center-align red lighten-3"> {{ post.title }} </h3>
<div class="card">
    <div class="card-content">
        {{ post.text }}
    </div>
    <div class="card-action">
        {{ post.created_at }}
    </div>
                
</div>
                
<a href="/blog" class="btn">Go Back</a>
<a class="btn btn-default" href="{% url 'blog:post_edit' id=post.id %}"><span class="glyphicon glyphicon-pencil"></span></a>

{% endblock %}




        

blog/templates/blog/edit.html
{% extends 'blog/base.html' %}


{% block content %}
<h1>New post</h1>
<form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

blog/templates/blog/form.html
 <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
 
    <script src="main.js"></script>
</head>
<body>

<div class="card-panel center-align">
     <h2><span class=" blue-text text-darken-2 ">{{ title }}</span> </h2>
</div>
    
<div class="container">
        <form>
                <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    
    </div>
</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
   
    {% for index in post %}
        <div class="row">
            <div class="col-sm-12">
                <div class="card text-center">
                    <div class="card-body">
                        <h5 class="card-title">{{ index.title }}</h5>
                        <a href="/blog/details/{{ index.id }}" class="btn btn-primary">Details</a>
                    </div>
                </div>
             </div>
            
        </div>
            
        {% endfor %} 

       

{% endblock %}
<!--
  {% for index in post %}
        <div class="row">
            <div class="col s12">
                    <li class="collection-item card-panel indigo lighten-4"><a href="/blog/details/{{ index.id }}">
                        {{ index.title }} </a></li>
            </div>
        </div>
    {% endfor %}
    -->    

    

blog/templates/blog/layout.html
{% load static %}
<html>
<head>
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> 
    <script src="main.js"></script>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo">Logo</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="sass.html">Sass</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">JavaScript</a></li>
            </ul>
        </div>
    </nav>
    <header class="container center-align">
        <h1>Blog Application</h1>
    </header>
    <div class="container">
        {%  block content %}
        {% endblock %}
    </div>
    <div class="center-align">
          <a href="/blog/signup.html" class="btn ">Register Here</a>
    </div>  
    

</body>
</html>

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}